//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 05:38:53 PM MSK 
//


package com.skat.smev.iasmkgu.model.packets;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.skat.smev.election package. 
 * <p>An RatesObjectFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class PacketsObjectFactory {


    /**
     * Create a new RatesObjectFactory that can be used to create new instances of schema derived classes for package: com.skat.smev.election
     * 
     */
    public PacketsObjectFactory() {
    }

    /**
     * Create an instance of {@link PacketsResponse }
     * 
     */
    public PacketsResponse createPacketsResponse() {
        return new PacketsResponse();
    }

    /**
     * Create an instance of {@link PacketsResponse.Packet }
     * 
     */
    public PacketsResponse.Packet createPacketsResponsePacket() {
        return new PacketsResponse.Packet();
    }

    /**
     * Create an instance of {@link PacketsRequest }
     * 
     */
    public PacketsRequest createPacketsRequest() {
        return new PacketsRequest();
    }

    /**
     * Create an instance of {@link VendorType }
     * 
     */
    public VendorType createVendorType() {
        return new VendorType();
    }

    /**
     * Create an instance of {@link ProcedureType }
     * 
     */
    public ProcedureType createProcedureType() {
        return new ProcedureType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link AuthorityType }
     * 
     */
    public AuthorityType createAuthorityType() {
        return new AuthorityType();
    }

}
