//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 05:38:53 PM MSK 
//


package com.skat.smev.iasmkgu.model.packets;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vendor" type="{http://vashkontrol.ru/service/common/types/1.1.0}VendorType"/>
 *         &lt;element name="packet-id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vendor",
    "packetId"
})
@XmlRootElement(name = "PacketsRequest", namespace = "http://vashkontrol.ru/service/packets/1.2.0")
public class PacketsRequest {

    @XmlElement(namespace = "http://vashkontrol.ru/service/packets/1.2.0", required = true)
    protected VendorType vendor;
    @XmlElement(name = "packet-id", namespace = "http://vashkontrol.ru/service/packets/1.2.0", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger packetId;

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link VendorType }
     *     
     */
    public VendorType getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorType }
     *     
     */
    public void setVendor(VendorType value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the packetId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPacketId() {
        return packetId;
    }

    /**
     * Sets the value of the packetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPacketId(BigInteger value) {
        this.packetId = value;
    }

}
