//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.11 at 11:34:24 PM MSK 
//


package com.skat.smev.iasmkgu.model.events;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.skat.smev.election package. 
 * <p>An EventsObjectFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class EventsObjectFactory {


    /**
     * Create a new EventsObjectFactory that can be used to create new instances of schema derived classes for package: com.skat.smev.election
     * 
     */
    public EventsObjectFactory() {
    }

    /**
     * Create an instance of {@link EventsResponse }
     * 
     */
    public EventsResponse createEventsResponse() {
        return new EventsResponse();
    }

    /**
     * Create an instance of {@link EventsRequest }
     * 
     */
    public EventsRequest createEventsRequest() {
        return new EventsRequest();
    }

    /**
     * Create an instance of {@link EventsRequest.Events }
     * 
     */
    public EventsRequest.Events createEventsRequestEvents() {
        return new EventsRequest.Events();
    }

    /**
     * Create an instance of {@link EventsResponse.Packet }
     * 
     */
    public EventsResponse.Packet createEventsResponsePacket() {
        return new EventsResponse.Packet();
    }

    /**
     * Create an instance of {@link EventsRequest.Vendor }
     * 
     */
    public EventsRequest.Vendor createEventsRequestVendor() {
        return new EventsRequest.Vendor();
    }

    /**
     * Create an instance of {@link VendorType }
     * 
     */
    public VendorType createVendorType() {
        return new VendorType();
    }

    /**
     * Create an instance of {@link EventsProcedureType }
     * 
     */
    public EventsProcedureType createProcedureType() {
        return new EventsProcedureType();
    }

    /**
     * Create an instance of {@link EventsServiceType }
     * 
     */
    public EventsServiceType createServiceType() {
        return new EventsServiceType();
    }

    /**
     * Create an instance of {@link EventsAuthorityType }
     * 
     */
    public EventsAuthorityType createAuthorityType() {
        return new EventsAuthorityType();
    }

    /**
     * Create an instance of {@link EventsRequest.Events.Event }
     * 
     */
    public EventsRequest.Events.Event createEventsRequestEventsEvent() {
        return new EventsRequest.Events.Event();
    }

}
