//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.11 at 11:34:24 PM MSK 
//


package com.skat.smev.iasmkgu.model.events;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vendor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="list-version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="events">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="event" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="mobile" type="{http://vashkontrol.ru/service/common/types/1.1.0}MobilePhoneNumberType"/>
 *                             &lt;element name="email" type="{http://vashkontrol.ru/service/common/types/1.1.0}EmailAddressType" minOccurs="0"/>
 *                             &lt;element name="authority" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsAuthorityType"/>
 *                             &lt;element name="service" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsServiceType"/>
 *                             &lt;element name="procedure" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsProcedureType" minOccurs="0"/>
 *                             &lt;element name="okato" type="{http://vashkontrol.ru/service/common/types/1.1.0}OKATOType"/>
 *                             &lt;element name="received-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="foreign-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vendor",
    "events"
})
@XmlRootElement(name = "EventsRequest", namespace = "http://vashkontrol.ru/service/events/1.2.0")
public class EventsRequest {

    @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
    protected EventsRequest.Vendor vendor;
    @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
    protected EventsRequest.Events events;

    /**
     * Gets the value of the vendor property.
     *
     * @return
     *     possible object is
     *     {@link EventsRequest.Vendor }
     *
     */
    public EventsRequest.Vendor getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     *
     * @param value
     *     allowed object is
     *     {@link EventsRequest.Vendor }
     *
     */
    public void setVendor(EventsRequest.Vendor value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the events property.
     *
     * @return
     *     possible object is
     *     {@link EventsRequest.Events }
     *
     */
    public EventsRequest.Events getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     *
     * @param value
     *     allowed object is
     *     {@link EventsRequest.Events }
     *
     */
    public void setEvents(EventsRequest.Events value) {
        this.events = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="event" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="mobile" type="{http://vashkontrol.ru/service/common/types/1.1.0}MobilePhoneNumberType"/>
     *                   &lt;element name="email" type="{http://vashkontrol.ru/service/common/types/1.1.0}EmailAddressType" minOccurs="0"/>
     *                   &lt;element name="authority" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsAuthorityType"/>
     *                   &lt;element name="service" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsServiceType"/>
     *                   &lt;element name="procedure" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsProcedureType" minOccurs="0"/>
     *                   &lt;element name="okato" type="{http://vashkontrol.ru/service/common/types/1.1.0}OKATOType"/>
     *                   &lt;element name="received-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="foreign-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "event"
    })
    public static class Events {

        @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
        protected List<Event> event;

        /**
         * Gets the value of the event property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the event property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvent().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EventsRequest.Events.Event }
         *
         *
         */
        public List<Event> getEvent() {
            if (event == null) {
                event = new ArrayList<Event>();
            }
            return this.event;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="mobile" type="{http://vashkontrol.ru/service/common/types/1.1.0}MobilePhoneNumberType"/>
         *         &lt;element name="email" type="{http://vashkontrol.ru/service/common/types/1.1.0}EmailAddressType" minOccurs="0"/>
         *         &lt;element name="authority" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsAuthorityType"/>
         *         &lt;element name="service" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsServiceType"/>
         *         &lt;element name="procedure" type="{http://vashkontrol.ru/service/common/types/1.1.0}EventsProcedureType" minOccurs="0"/>
         *         &lt;element name="okato" type="{http://vashkontrol.ru/service/common/types/1.1.0}OKATOType"/>
         *         &lt;element name="received-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *       &lt;attribute name="foreign-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mobile",
            "email",
            "authority",
            "service",
            "procedure",
            "okato",
            "receivedDate"
        })
        public static class Event {

            @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
            protected String mobile;
            @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0")
            protected String email;
            @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
            protected EventsAuthorityType authority;
            @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
            protected EventsServiceType service;
            @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0")
            protected EventsProcedureType procedure;
            @XmlElement(namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
            protected String okato;
            @XmlElement(name = "received-date", namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar receivedDate;
            @XmlAttribute(name = "foreign-id", required = true)
            protected String foreignId;

            /**
             * Gets the value of the mobile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMobile() {
                return mobile;
            }

            /**
             * Sets the value of the mobile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMobile(String value) {
                this.mobile = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

            /**
             * Gets the value of the authority property.
             * 
             * @return
             *     possible object is
             *     {@link EventsAuthorityType }
             *     
             */
            public EventsAuthorityType getAuthority() {
                return authority;
            }

            /**
             * Sets the value of the authority property.
             * 
             * @param value
             *     allowed object is
             *     {@link EventsAuthorityType }
             *     
             */
            public void setAuthority(EventsAuthorityType value) {
                this.authority = value;
            }

            /**
             * Gets the value of the service property.
             * 
             * @return
             *     possible object is
             *     {@link EventsServiceType }
             *     
             */
            public EventsServiceType getService() {
                return service;
            }

            /**
             * Sets the value of the service property.
             * 
             * @param value
             *     allowed object is
             *     {@link EventsServiceType }
             *     
             */
            public void setService(EventsServiceType value) {
                this.service = value;
            }

            /**
             * Gets the value of the procedure property.
             * 
             * @return
             *     possible object is
             *     {@link EventsProcedureType }
             *     
             */
            public EventsProcedureType getProcedure() {
                return procedure;
            }

            /**
             * Sets the value of the procedure property.
             * 
             * @param value
             *     allowed object is
             *     {@link EventsProcedureType }
             *     
             */
            public void setProcedure(EventsProcedureType value) {
                this.procedure = value;
            }

            /**
             * Gets the value of the okato property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOkato() {
                return okato;
            }

            /**
             * Sets the value of the okato property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOkato(String value) {
                this.okato = value;
            }

            /**
             * Gets the value of the receivedDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getReceivedDate() {
                return receivedDate;
            }

            /**
             * Sets the value of the receivedDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setReceivedDate(XMLGregorianCalendar value) {
                this.receivedDate = value;
            }

            /**
             * Gets the value of the foreignId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getForeignId() {
                return foreignId;
            }

            /**
             * Sets the value of the foreignId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setForeignId(String value) {
                this.foreignId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="list-version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listVersion"
    })
    public static class Vendor {

        @XmlElement(name = "list-version", namespace = "http://vashkontrol.ru/service/events/1.2.0", required = true)
        protected String listVersion;
        @XmlAttribute(name = "id", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger id;

        /**
         * Gets the value of the listVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getListVersion() {
            return listVersion;
        }

        /**
         * Sets the value of the listVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setListVersion(String value) {
            this.listVersion = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

    }

}
