//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.11 at 11:34:24 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vashkontrol.ru/service/common/types/1.1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.skat.smev.iasmkgu.model.events;
