//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.12 at 12:26:53 AM MSK 
//


package com.skat.smev.iasmkgu.model.forms;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="form">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="monitoring_id" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="service-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="blocks">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="block" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="indicators">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="indicator" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="values">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="alt-title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                               &lt;attribute name="data-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="view-as" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="block-id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "form",
    "blocks",
    "indicators"
})
@XmlRootElement(name = "FormsResponse", namespace = "http://vashkontrol.ru/service/forms/1.2.0")
public class FormsResponse {

    @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
    protected FormsResponse.Form form;
    @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
    protected FormsResponse.Blocks blocks;
    @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
    protected FormsResponse.Indicators indicators;

    /**
     * Gets the value of the form property.
     *
     * @return
     *     possible object is
     *     {@link FormsResponse.Form }
     *
     */
    public FormsResponse.Form getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     *
     * @param value
     *     allowed object is
     *     {@link FormsResponse.Form }
     *
     */
    public void setForm(FormsResponse.Form value) {
        this.form = value;
    }

    /**
     * Gets the value of the blocks property.
     *
     * @return
     *     possible object is
     *     {@link FormsResponse.Blocks }
     *
     */
    public FormsResponse.Blocks getBlocks() {
        return blocks;
    }

    /**
     * Sets the value of the blocks property.
     *
     * @param value
     *     allowed object is
     *     {@link FormsResponse.Blocks }
     *
     */
    public void setBlocks(FormsResponse.Blocks value) {
        this.blocks = value;
    }

    /**
     * Gets the value of the indicators property.
     *
     * @return
     *     possible object is
     *     {@link FormsResponse.Indicators }
     *
     */
    public FormsResponse.Indicators getIndicators() {
        return indicators;
    }

    /**
     * Sets the value of the indicators property.
     *
     * @param value
     *     allowed object is
     *     {@link FormsResponse.Indicators }
     *
     */
    public void setIndicators(FormsResponse.Indicators value) {
        this.indicators = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="block" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "block"
    })
    public static class Blocks {

        @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0")
        protected List<Block> block;

        /**
         * Gets the value of the block property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the block property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBlock().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FormsResponse.Blocks.Block }
         *
         *
         */
        public List<Block> getBlock() {
            if (block == null) {
                block = new ArrayList<Block>();
            }
            return this.block;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Block {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected Byte id;
            @XmlAttribute(name = "queue")
            protected String queue;
            @XmlAttribute(name = "optional")
            protected String optional;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             *
             * @return
             *     possible object is
             *     {@link Byte }
             *
             */
            public Byte getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value
             *     allowed object is
             *     {@link Byte }
             *
             */
            public void setId(Byte value) {
                this.id = value;
            }

            /**
             * Gets the value of the queue property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getQueue() {
                return queue;
            }

            /**
             * Sets the value of the queue property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setQueue(String value) {
                this.queue = value;
            }

            /**
             * Gets the value of the optional property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getOptional() {
                return optional;
            }

            /**
             * Sets the value of the optional property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setOptional(String value) {
                this.optional = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="monitoring_id" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="service-type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "updatedAt",
        "monitoringId"
    })
    public static class Form {

        @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
        protected String version;
        @XmlElement(name = "updated_at", namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
        protected String updatedAt;
        @XmlElement(name = "monitoring_id", namespace = "http://vashkontrol.ru/service/forms/1.2.0")
        protected Byte monitoringId;
        @XmlAttribute(name = "service-type")
        protected String serviceType;

        /**
         * Gets the value of the version property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the updatedAt property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getUpdatedAt() {
            return updatedAt;
        }

        /**
         * Sets the value of the updatedAt property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setUpdatedAt(String value) {
            this.updatedAt = value;
        }

        /**
         * Gets the value of the monitoringId property.
         *
         * @return
         *     possible object is
         *     {@link Byte }
         *
         */
        public Byte getMonitoringId() {
            return monitoringId;
        }

        /**
         * Sets the value of the monitoringId property.
         *
         * @param value
         *     allowed object is
         *     {@link Byte }
         *
         */
        public void setMonitoringId(Byte value) {
            this.monitoringId = value;
        }

        /**
         * Gets the value of the serviceType property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getServiceType() {
            return serviceType;
        }

        /**
         * Sets the value of the serviceType property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setServiceType(String value) {
            this.serviceType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="indicator" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="values">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="alt-title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                                     &lt;attribute name="data-type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="view-as" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="block-id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "indicator"
    })
    public static class Indicators {

        @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0")
        protected List<Indicator> indicator;

        /**
         * Gets the value of the indicator property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the indicator property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIndicator().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FormsResponse.Indicators.Indicator }
         *
         *
         */
        public List<Indicator> getIndicator() {
            if (indicator == null) {
                indicator = new ArrayList<Indicator>();
            }
            return this.indicator;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="values">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="alt-title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                           &lt;attribute name="data-type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="view-as" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="block-id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "description",
            "values"
        })
        public static class Indicator {

            @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
            protected String title;
            @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
            protected String description;
            @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
            protected FormsResponse.Indicators.Indicator.Values values;
            @XmlAttribute(name = "id")
            protected Byte id;
            @XmlAttribute(name = "queue")
            protected Byte queue;
            @XmlAttribute(name = "view-as")
            protected String viewAs;
            @XmlAttribute(name = "block-id")
            protected Byte blockId;

            /**
             * Gets the value of the title property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the description property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the values property.
             *
             * @return
             *     possible object is
             *     {@link FormsResponse.Indicators.Indicator.Values }
             *
             */
            public FormsResponse.Indicators.Indicator.Values getValues() {
                return values;
            }

            /**
             * Sets the value of the values property.
             *
             * @param value
             *     allowed object is
             *     {@link FormsResponse.Indicators.Indicator.Values }
             *
             */
            public void setValues(FormsResponse.Indicators.Indicator.Values value) {
                this.values = value;
            }

            /**
             * Gets the value of the id property.
             *
             * @return
             *     possible object is
             *     {@link Byte }
             *
             */
            public Byte getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value
             *     allowed object is
             *     {@link Byte }
             *
             */
            public void setId(Byte value) {
                this.id = value;
            }

            /**
             * Gets the value of the queue property.
             *
             * @return
             *     possible object is
             *     {@link Byte }
             *
             */
            public Byte getQueue() {
                return queue;
            }

            /**
             * Sets the value of the queue property.
             *
             * @param value
             *     allowed object is
             *     {@link Byte }
             *
             */
            public void setQueue(Byte value) {
                this.queue = value;
            }

            /**
             * Gets the value of the viewAs property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getViewAs() {
                return viewAs;
            }

            /**
             * Sets the value of the viewAs property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setViewAs(String value) {
                this.viewAs = value;
            }

            /**
             * Gets the value of the blockId property.
             *
             * @return
             *     possible object is
             *     {@link Byte }
             *
             */
            public Byte getBlockId() {
                return blockId;
            }

            /**
             * Sets the value of the blockId property.
             *
             * @param value
             *     allowed object is
             *     {@link Byte }
             *
             */
            public void setBlockId(Byte value) {
                this.blockId = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="alt-title" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *                 &lt;attribute name="data-type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Values {

                @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0")
                protected List<Value> value;

                /**
                 * Gets the value of the value property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the value property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getValue().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FormsResponse.Indicators.Indicator.Values.Value }
                 *
                 *
                 */
                public List<Value> getValue() {
                    if (value == null) {
                        value = new ArrayList<Value>();
                    }
                    return this.value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="alt-title" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
                 *       &lt;attribute name="data-type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "title",
                    "altTitle",
                    "description",
                    "min",
                    "max"
                })
                public static class Value {

                    @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
                    protected String title;
                    @XmlElement(name = "alt-title", namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
                    protected String altTitle;
                    @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
                    protected String description;
                    @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
                    protected String min;
                    @XmlElement(namespace = "http://vashkontrol.ru/service/forms/1.2.0", required = true)
                    protected String max;
                    @XmlAttribute(name = "id")
                    protected Byte id;
                    @XmlAttribute(name = "data-type")
                    protected String dataType;

                    /**
                     * Gets the value of the title property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTitle() {
                        return title;
                    }

                    /**
                     * Sets the value of the title property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTitle(String value) {
                        this.title = value;
                    }

                    /**
                     * Gets the value of the altTitle property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAltTitle() {
                        return altTitle;
                    }

                    /**
                     * Sets the value of the altTitle property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAltTitle(String value) {
                        this.altTitle = value;
                    }

                    /**
                     * Gets the value of the description property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDescription() {
                        return description;
                    }

                    /**
                     * Sets the value of the description property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDescription(String value) {
                        this.description = value;
                    }

                    /**
                     * Gets the value of the min property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getMin() {
                        return min;
                    }

                    /**
                     * Sets the value of the min property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setMin(String value) {
                        this.min = value;
                    }

                    /**
                     * Gets the value of the max property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getMax() {
                        return max;
                    }

                    /**
                     * Sets the value of the max property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setMax(String value) {
                        this.max = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setId(Byte value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the dataType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDataType() {
                        return dataType;
                    }

                    /**
                     * Sets the value of the dataType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDataType(String value) {
                        this.dataType = value;
                    }

                }

            }

        }

    }

}
