//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.12 at 12:26:53 AM MSK 
//


package com.skat.smev.iasmkgu.model.forms;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.skat.smev.election package. 
 * <p>An FormsObjectFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class FormsObjectFactory {


    /**
     * Create a new FormsObjectFactory that can be used to create new instances of schema derived classes for package: com.skat.smev.election
     * 
     */
    public FormsObjectFactory() {
    }

    /**
     * Create an instance of {@link FormsResponse }
     * 
     */
    public FormsResponse createFormsResponse() {
        return new FormsResponse();
    }

    /**
     * Create an instance of {@link FormsResponse.Indicators }
     * 
     */
    public FormsResponse.Indicators createFormsResponseIndicators() {
        return new FormsResponse.Indicators();
    }

    /**
     * Create an instance of {@link FormsResponse.Indicators.Indicator }
     * 
     */
    public FormsResponse.Indicators.Indicator createFormsResponseIndicatorsIndicator() {
        return new FormsResponse.Indicators.Indicator();
    }

    /**
     * Create an instance of {@link FormsResponse.Indicators.Indicator.Values }
     * 
     */
    public FormsResponse.Indicators.Indicator.Values createFormsResponseIndicatorsIndicatorValues() {
        return new FormsResponse.Indicators.Indicator.Values();
    }

    /**
     * Create an instance of {@link FormsResponse.Blocks }
     * 
     */
    public FormsResponse.Blocks createFormsResponseBlocks() {
        return new FormsResponse.Blocks();
    }

    /**
     * Create an instance of {@link FormsRequest }
     * 
     */
    public FormsRequest createFormsRequest() {
        return new FormsRequest();
    }

    /**
     * Create an instance of {@link VendorType }
     * 
     */
    public VendorType createVendorType() {
        return new VendorType();
    }

    /**
     * Create an instance of {@link FormsResponse.Form }
     * 
     */
    public FormsResponse.Form createFormsResponseForm() {
        return new FormsResponse.Form();
    }

    /**
     * Create an instance of {@link ProcedureType }
     * 
     */
    public ProcedureType createProcedureType() {
        return new ProcedureType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link FormsAuthorityType }
     * 
     */
    public FormsAuthorityType createAuthorityType() {
        return new FormsAuthorityType();
    }

    /**
     * Create an instance of {@link FormsResponse.Indicators.Indicator.Values.Value }
     * 
     */
    public FormsResponse.Indicators.Indicator.Values.Value createFormsResponseIndicatorsIndicatorValuesValue() {
        return new FormsResponse.Indicators.Indicator.Values.Value();
    }

    /**
     * Create an instance of {@link FormsResponse.Blocks.Block }
     * 
     */
    public FormsResponse.Blocks.Block createFormsResponseBlocksBlock() {
        return new FormsResponse.Blocks.Block();
    }

}
