//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.19 at 06:13:30 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vashkontrol.ru/service/rates/1.2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.skat.smev.iasmkgu.model.rates;
