//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.19 at 06:13:30 PM MSK 
//


package com.skat.smev.iasmkgu.model.rates;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vendor" type="{http://vashkontrol.ru/service/common/types/1.1.0}VendorType"/>
 *         &lt;element name="forms">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="form" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="data" type="{http://vashkontrol.ru/service/rates/1.2.0}DataType" minOccurs="0"/>
 *                             &lt;element name="rates">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="rate" type="{http://vashkontrol.ru/service/rates/1.2.0}RateType" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="db-id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="foreign-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vendor",
    "forms"
})
@XmlRootElement(name = "RatesRequest")
public class RatesRequest {

    @XmlElement(required = true)
    protected VendorType vendor;
    @XmlElement(required = true)
    protected RatesRequest.Forms forms;

    /**
     * Gets the value of the vendor property.
     *
     * @return
     *     possible object is
     *     {@link VendorType }
     *
     */
    public VendorType getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     *
     * @param value
     *     allowed object is
     *     {@link VendorType }
     *
     */
    public void setVendor(VendorType value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the forms property.
     *
     * @return
     *     possible object is
     *     {@link RatesRequest.Forms }
     *
     */
    public RatesRequest.Forms getForms() {
        return forms;
    }

    /**
     * Sets the value of the forms property.
     *
     * @param value
     *     allowed object is
     *     {@link RatesRequest.Forms }
     *
     */
    public void setForms(RatesRequest.Forms value) {
        this.forms = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="form" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="data" type="{http://vashkontrol.ru/service/rates/1.2.0}DataType" minOccurs="0"/>
     *                   &lt;element name="rates">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="rate" type="{http://vashkontrol.ru/service/rates/1.2.0}RateType" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="db-id" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="foreign-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "form"
    })
    public static class Forms {

        @XmlElement(required = true)
        protected List<Form> form;

        /**
         * Gets the value of the form property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the form property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getForm().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RatesRequest.Forms.Form }
         *
         *
         */
        public List<Form> getForm() {
            if (form == null) {
                form = new ArrayList<Form>();
            }
            return this.form;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="data" type="{http://vashkontrol.ru/service/rates/1.2.0}DataType" minOccurs="0"/>
         *         &lt;element name="rates">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="rate" type="{http://vashkontrol.ru/service/rates/1.2.0}RateType" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="db-id" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="foreign-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "data",
            "rates"
        })
        public static class Form {

            protected DataType data;
            @XmlElement(required = true)
            protected RatesRequest.Forms.Form.Rates rates;
            @XmlAttribute(name = "db-id")
            protected BigInteger mkguId;
            @XmlAttribute(name = "foreign-id", required = true)
            protected String foreignId;

            /**
             * Gets the value of the data property.
             *
             * @return
             *     possible object is
             *     {@link DataType }
             *
             */
            public DataType getData() {
                return data;
            }

            /**
             * Sets the value of the data property.
             *
             * @param value
             *     allowed object is
             *     {@link DataType }
             *
             */
            public void setData(DataType value) {
                this.data = value;
            }

            /**
             * Gets the value of the rates property.
             *
             * @return
             *     possible object is
             *     {@link RatesRequest.Forms.Form.Rates }
             *
             */
            public RatesRequest.Forms.Form.Rates getRates() {
                return rates;
            }

            /**
             * Sets the value of the rates property.
             *
             * @param value
             *     allowed object is
             *     {@link RatesRequest.Forms.Form.Rates }
             *
             */
            public void setRates(RatesRequest.Forms.Form.Rates value) {
                this.rates = value;
            }

            /**
             * Gets the value of the mkguId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMkguId() {
                return mkguId;
            }

            /**
             * Sets the value of the mkguId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMkguId(BigInteger value) {
                this.mkguId = value;
            }

            /**
             * Gets the value of the foreignId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getForeignId() {
                return foreignId;
            }

            /**
             * Sets the value of the foreignId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setForeignId(String value) {
                this.foreignId = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="rate" type="{http://vashkontrol.ru/service/rates/1.2.0}RateType" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "rate"
            })
            public static class Rates {

                @XmlElement(required = true)
                protected List<RateType> rate;

                /**
                 * Gets the value of the rate property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the rate property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getRate().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link RateType }
                 * 
                 * 
                 */
                public List<RateType> getRate() {
                    if (rate == null) {
                        rate = new ArrayList<RateType>();
                    }
                    return this.rate;
                }

            }

        }

    }

}
